import {
  Country,
  City,
  Attraction,
  Restaurant,
  Activity,
  TravelTip,
} from "./types";

export const mockCountries: Country[] = [
  {
    id: "italy",
    name: "Italy",
    code: "IT",
    description: "Experience art, culture, and culinary excellence",
    image: "https://picsum.photos/500/300?random=2",
  },
  {
    id: "japan",
    name: "Japan",
    code: "JP",
    description: "Blend of ancient tradition and cutting-edge modernity",
    image: "https://picsum.photos/500/300?random=5",
  },
  {
    id: "spain",
    name: "Spain",
    code: "ES",
    description: "Vibrant culture, passion, and Mediterranean beauty",
    image: "https://picsum.photos/500/300?random=7",
  },
  {
    id: "france",
    name: "France",
    code: "FR",
    description: "Romance, art, and world-class cuisine",
    image: "https://picsum.photos/500/300?random=9",
  },
  {
    id: "thailand",
    name: "Thailand",
    code: "TH",
    description: "Exotic beaches, temples, and rich Buddhist culture",
    image: "https://picsum.photos/500/300?random=11",
  },
  {
    id: "greece",
    name: "Greece",
    code: "GR",
    description: "Ancient wonders, island paradise, and Mediterranean charm",
    image: "https://picsum.photos/500/300?random=13",
  },
  {
    id: "mexico",
    name: "Mexico",
    code: "MX",
    description: "Vibrant culture, ancient ruins, and beautiful beaches",
    image: "https://picsum.photos/500/300?random=15",
  },
  {
    id: "uk",
    name: "United Kingdom",
    code: "GB",
    description: "History, royal heritage, and charming countryside",
    image: "https://picsum.photos/500/300?random=17",
  },
  {
    id: "portugal",
    name: "Portugal",
    code: "PT",
    description: "Coastal beauty, historic charm, and vibrant culture",
    image: "https://picsum.photos/500/300?random=20",
  },
  {
    id: "australia",
    name: "Australia",
    code: "AU",
    description: "Iconic landmarks, stunning nature, and adventure",
    image: "https://picsum.photos/500/300?random=22",
  },
  {
    id: "brazil",
    name: "Brazil",
    code: "BR",
    description: "Tropical paradise, vibrant cities, and natural wonders",
    image: "https://picsum.photos/500/300?random=24",
  },
  {
    id: "egypt",
    name: "Egypt",
    code: "EG",
    description: "Ancient pyramids, Nile River, and timeless wonders",
    image: "https://picsum.photos/500/300?random=26",
  },
];

export const mockCities: City[] = [
  {
    id: "rome",
    countryId: "italy",
    name: "Rome",
    description: "The Eternal City - A living museum of history and art",
    image: "https://picsum.photos/800/500?random=13",
    knownFor: [
      "Colosseum",
      "Vatican City",
      "Ancient History",
      "Incredible Food",
      "Romantic Streets",
    ],
    climate: "Temperate Mediterranean",
    bestTimeToVisit: "April-May, September-October",
    introText:
      "Walk through millennia of history in Rome, where ancient ruins stand beside Renaissance art and world-class cuisine at every corner. Experience the grandeur of the Vatican, the majesty of the Colosseum, and the charm of cobblestone streets.",
    isFavorite: false,
    lat: 41.9028,
    lng: 12.4964,
    priority: 10,
  },
  {
    id: "tokyo",
    countryId: "japan",
    name: "Tokyo",
    description: "Ultra-modern metropolis where ancient temples meet neon-lit streets",
    image: "https://picsum.photos/800/500?random=17",
    knownFor: [
      "Technology",
      "Street Food",
      "Temples",
      "Nightlife",
      "Pop Culture",
    ],
    climate: "Temperate with four seasons",
    bestTimeToVisit: "March-May, September-November",
    introText:
      "Discover the perfect harmony of traditional and modern in Tokyo. From serene temples and cherry blossoms to cutting-edge technology and vibrant nightlife, Tokyo offers an unforgettable blend of experiences.",
    isFavorite: false,
    lat: 35.6762,
    lng: 139.6503,
    priority: 10,
  },
  {
    id: "barcelona",
    countryId: "spain",
    name: "Barcelona",
    description: "Gaudí's architectural masterpiece by the Mediterranean Sea",
    image: "https://picsum.photos/800/500?random=20",
    knownFor: [
      "Sagrada Família",
      "Park Güell",
      "Beaches",
      "Tapas & Wine",
      "FC Barcelona",
    ],
    climate: "Mediterranean",
    bestTimeToVisit: "April-May, September-October",
    introText:
      "Experience Barcelona's unique charm with its stunning Gaudí architecture, golden beaches, and passionate food and wine culture. From modernist masterpieces to vibrant neighborhoods, Barcelona inspired.",
    isFavorite: false,
    lat: 41.3851,
    lng: 2.1734,
    priority: 10,
  },
  {
    id: "paris",
    countryId: "france",
    name: "Paris",
    description: "The City of Light - Elegance, art, and romance",
    image:
      "https://picsum.photos/800/500?random=24",
    knownFor: [
      "Eiffel Tower",
      "Louvre Museum",
      "Cafés",
      "Fashion",
      "Fine Dining",
    ],
    climate: "Temperate",
    bestTimeToVisit: "April-May, September-October",
    introText:
      "Stroll along the Seine, visit world-class museums, and enjoy exquisite cuisine in the world's most romantic city. Paris captures hearts with its timeless elegance and joie de vivre.",
    isFavorite: false,
    lat: 48.8566,
    lng: 2.3522,
    priority: 10,
  },
  {
    id: "bangkok",
    countryId: "thailand",
    name: "Bangkok",
    description:
      "Vibrant capital where ancient temples meet modern chaos and incredible street food",
    image:
      "https://picsum.photos/800/500?random=27",
    knownFor: [
      "Street Food",
      "Night Markets",
      "Temples",
      "Nightlife",
      "Shopping",
    ],
    climate: "Tropical",
    bestTimeToVisit: "November-February",
    lat: 13.7563,
    lng: 100.5018,
    priority: 9,
    introText:
      "Immerse yourself in Bangkok's electric energy. Navigate bustling markets, marvel at ornate temples, savor world-famous street food, and experience a city that never sleeps.",
    isFavorite: false,
  },
  {
    id: "amsterdam",
    countryId: "uk",
    name: "Amsterdam",
    description: "Charming canals, world-class museums, and bike culture",
    image: "https://picsum.photos/800/500?random=31",
    knownFor: ["Canals", "Bikes", "Museums", "Anne Frank House", "Tulips"],
    climate: "Temperate maritime",
    lat: 52.3676,
    lng: 4.9041,
    priority: 9,
    bestTimeToVisit: "April-May, September",
    introText: "Cycle through picturesque canals and charming neighborhoods in Amsterdam. Discover masterpieces in world-renowned museums and experience the laid-back Dutch lifestyle.",
    isFavorite: false,
  },
  {
    id: "athens",
    countryId: "greece",
    name: "Athens",
    description: "Ancient Greek history meets modern European city",
    lat: 37.9838,
    lng: 23.7275,
    priority: 9,
    image: "https://picsum.photos/800/500?random=34",
    knownFor: ["Parthenon", "Ancient Ruins", "Greek Culture", "Mediterranean Food", "Nightlife"],
    climate: "Mediterranean",
    bestTimeToVisit: "April-May, September-October",
    introText: "Walk in the footsteps of Socrates and Aristotle in Athens. Marvel at the iconic Parthenon, explore ancient ruins, and indulge in authentic Greek cuisine in bustling tavernas.",
    isFavorite: false,
  },
  {
    id: "mexico-city",
    lat: 19.4326,
    lng: -99.1332,
    priority: 10,
    countryId: "mexico",
    name: "Mexico City",
    description: "Vibrant capital with rich history and incredible cuisine",
    image: "https://picsum.photos/800/500?random=37",
    knownFor: ["Frida Kahlo Museum", "Historic Center", "Street Food", "Ancient Pyramids", "Artistic Culture"],
    climate: "Subtropical highland",
    bestTimeToVisit: "October-April",
    introText: "Immerse yourself in the heart of Mexican culture. Explore ancient Aztec ruins, admire world-class museums, savor some of the planet's best cuisine, and experience vibrant neighborhood markets.",
    isFavorite: false,
    lat: 51.5074,
    lng: -0.1278,
    priority: 10,
  },
  {
    id: "london",
    countryId: "uk",
    name: "London",
    description: "Historic capital with royal heritage and modern energy",
    image: "https://picsum.photos/800/500?random=40",
    knownFor: ["Big Ben", "Buckingham Palace", "British Museum", "Tower Bridge", "Theatre District"],
    climate: "Temperate maritime",
    lat: 38.7223,
    lng: -9.1393,
    priority: 9,
    bestTimeToVisit: "June-August, December",
    introText: "Experience the blend of royal heritage and cutting-edge modernity in London. Visit iconic landmarks, explore world-class museums, enjoy West End theatre, and discover hidden pubs and markets.",
    isFavorite: false,
  },
  {
    id: "lisbon",
    countryId: "portugal",
    name: "Lisbon",
    description: "Charming hilltop city with pastéis de nata and Atlantic views",
    lat: -33.8688,
    lng: 151.2093,
    priority: 10,
    image: "https://picsum.photos/800/500?random=43",
    knownFor: ["Tram 28", "Pastéis de Nata", "Sintra Castles", "Sunset Views", "Blue Tiles"],
    climate: "Mediterranean",
    bestTimeToVisit: "April-May, September-October",
    introText: "Climb the historic hills of Lisbon and discover a city of pastel buildings, ancient tiles, and simple pleasures. Ride the famous tram 28, taste Pastéis de Nata, and watch the sunset from Miradouro viewpoints.",
    isFavorite: false,
  },
  {
    id: "sydney",
    countryId: "australia",
    name: "Sydney",
    description: "Iconic harbor city with beaches and vibrant culture",
    lat: -22.9068,
    lng: -43.1729,
    priority: 10,
    image: "https://picsum.photos/800/500?random=47",
    knownFor: ["Opera House", "Sydney Harbour Bridge", "Bondi Beach", "Scenic Coastal Walks", "Coffee Culture"],
    climate: "Temperate",
    bestTimeToVisit: "September-November, March-May",
    introText: "Discover the magic of Sydney, where the iconic Opera House meets stunning beaches and vibrant neighborhoods. Swim at Bondi, hike coastal trails, and experience the laid-back Australian lifestyle.",
    isFavorite: false,
  },
  {
    id: "rio-de-janeiro",
    lat: 30.0444,
    lng: 31.2357,
    priority: 10,
    countryId: "brazil",
    name: "Rio de Janeiro",
    description: "Stunning beaches, mountains, and vibrant party atmosphere",
    image: "https://picsum.photos/800/500?random=50",
    knownFor: ["Christ the Redeemer", "Copacabana Beach", "Carnival", "Sugar Loaf Mountain", "Ipanema"],
    climate: "Tropical",
    bestTimeToVisit: "March (Carnival), December-February",
    introText: "Feel the heartbeat of Brazil in Rio. Gaze upon the magnificent Christ the Redeemer statue, relax on world-famous beaches, and experience the infectious energy of this passionate city and its legendary Carnival.",
    isFavorite: false,
    lat: 45.4408,
    lng: 12.3155,
    priority: 10,
  },
  {
    id: "cairo",
    countryId: "egypt",
    name: "Cairo",
    description: "Gateway to ancient Egyptian wonders and modern Nile culture",
    image: "https://picsum.photos/800/500?random=53",
    knownFor: ["Pyramids of Giza", "Egyptian Museum", "Nile River Cruises", "Khan el-Khalili Bazaar", "Islamic Architecture"],
    climate: "Desert",
    lat: 35.0116,
    lng: 135.7681,
    priority: 10,
    bestTimeToVisit: "October-April",
    introText: "Stand in awe before the Great Pyramids of Giza, one of the world's greatest wonders. Explore ancient artifacts in the Egyptian Museum, cruise the Nile, and haggle in bustling bazaars.",
    isFavorite: false,
  },
  {
    id: "venice",
    countryId: "italy",
    name: "Venice",
    description: "Romantic canal city with Renaissance art and architecture",
    lat: 40.4168,
    lng: -3.7038,
    priority: 10,
    image: "https://picsum.photos/800/500?random=57",
    knownFor: ["Grand Canal", "St. Mark's Basilica", "Gondola Rides", "Venetian Masks", "Bridges"],
    climate: "Mediterranean",
    bestTimeToVisit: "April-May, September-October",
    introText: "Drift through the enchanting canals of Venice in a gondola. Admire Renaissance art, explore hidden squares, and experience the romance of this unique city built on water.",
    isFavorite: false,
  },
  {
    id: "kyoto",
    lat: 43.7102,
    lng: 7.2620,
    priority: 8,
    countryId: "japan",
    name: "Kyoto",
    description: "Cultural heart of Japan with thousands of temples and gardens",
    image: "https://picsum.photos/800/500?random=60",
    knownFor: ["Fushimi Inari Gates", "Temples", "Cherry Blossoms", "Geisha Culture", "Traditional Gardens"],
    climate: "Temperate",
    bestTimeToVisit: "March-April, October-November",
    introText: "Step back in time in Kyoto, where ancient temples and traditional gardens transport you to medieval Japan. Walk among thousands of red torii gates and encounter geishas in traditional districts.",
    isFavorite: false,
  },
  {
    id: "madrid",
    countryId: "spain",
    name: "Madrid",
    description: "Sophisticated capital with world-class museums and vibrant nightlife",
    image: "https://picsum.photos/800/500?random=63",
    knownFor: ["Prado Museum", "Royal Palace", "Flamenco Dancing", "Tapas Bars", "Park Retiro"],
    climate: "Mediterranean continental",
    bestTimeToVisit: "September-November, March-May",
    introText: "Experience Spain's sophisticated capital with its world-class museums, royal palaces, and passionate flamenco performances. Enjoy traditional tapas in historic taverns and vibrant late-night culture.",
    isFavorite: false,
  },
  {
    id: "nice",
    countryId: "france",
    name: "Nice",
    description: "Glamorous French Riviera city with pebble beaches and old town charm",
    image: "https://picsum.photos/800/500?random=67",
    knownFor: ["Promenade des Anglais", "Pebble Beaches", "Old Town", "Mediterranean View", "French Riviera"],
    climate: "Mediterranean",
    bestTimeToVisit: "April-May, September-October",
    introText: "Stroll the elegant Promenade des Anglais in Nice, where the French Riviera's charm meets modern elegance. Enjoy Mediterranean beaches, explore the colorful old town, and savor Provençal cuisine.",
    isFavorite: false,
  },
];

export const mockAttractions: Attraction[] = [
  {
    id: "colosseum-rome",
    cityId: "rome",
    name: "The Colosseum",
    description:
      "Ancient amphitheater and iconic symbol of Rome, hosting gladiator battles centuries ago",
    type: "must-see",
    image:
      "https://picsum.photos/600/400?random=92",
    location: "Piazza del Colosseo",
    tips: "Book tickets online in advance. Go early morning or late evening to avoid crowds. Allow 1-2 hours for visit.",
    whyRecommended: [
      "Iconic and historic",
      "Stunning architecture",
      "Educational experience",
    ],
    tags: ["history", "culture", "art"],
    targetAgeGroups: ["25-34", "35-49", "50-64", "65+"],
  },
  {
    id: "vatican-rome",
    cityId: "rome",
    name: "Vatican City",
    description:
      "World's smallest sovereign state housing St. Peter's Basilica and the Sistine Chapel",
    type: "must-see",
    image:
      "https://picsum.photos/600/400?random=97",
    location: "Vatican City",
    tips: "Dress modestly. Allow at least 3 hours. Visit early morning for fewer crowds.",
    whyRecommended: ["Spiritual significance", "Artistic masterpiece", "UNESCO site"],
    tags: ["history", "culture", "art"],
    targetAgeGroups: ["25-34", "35-49", "50-64", "65+"],
  },
  {
    id: "trevi-fountain",
    cityId: "rome",
    name: "Trevi Fountain",
    description:
      "Baroque fountain and one of Rome's most iconic landmarks, beautifully illuminated at night",
    type: "must-see",
    image:
      "https://picsum.photos/600/400?random=1",
    location: "Piazza di Trevi",
    tips: "Go at night for a magical experience. Arrive early morning to avoid daytime crowds.",
    whyRecommended: ["Stunning architecture", "Romantic ambiance", "Photo opportunities"],
    tags: ["art", "culture"],
    targetAgeGroups: ["18-24", "25-34", "35-49"],
  },
  {
    id: "pantheon-rome",
    cityId: "rome",
    name: "Pantheon",
    description:
      "Remarkably preserved Roman temple with a magnificent dome and oculus opening to the sky",
    type: "must-see",
    image:
      "https://picsum.photos/600/400?random=5",
    location: "Piazza della Rotonda",
    tips: "Visit on a sunny day to see the light streaming through the oculus. Entry is free.",
    whyRecommended: ["Architectural marvel", "Historical significance", "Free entry"],
    tags: ["history", "architecture", "culture"],
    targetAgeGroups: ["25-34", "35-49", "50-64", "65+"],
  },
  {
    id: "senso-ji-tokyo",
    cityId: "tokyo",
    name: "Senso-ji Temple",
    description: "Tokyo's oldest temple, famous for its iconic red lantern and bustling atmosphere",
    type: "must-see",
    image:
      "https://picsum.photos/600/400?random=9",
    location: "Asakusa",
    tips: "Visit early morning for a peaceful experience. Don't miss the shopping street with souvenirs.",
    whyRecommended: ["Authentic Tokyo experience", "Spiritual atmosphere", "Historic temple"],
    tags: ["culture", "history", "art"],
    targetAgeGroups: ["18-24", "25-34", "35-49", "50-64", "65+"],
  },
  {
    id: "tokyo-tower",
    cityId: "tokyo",
    name: "Tokyo Tower",
    description:
      "Iconic red tower offering panoramic 360-degree views of Tokyo from its observation decks",
    type: "must-see",
    image:
      "https://picsum.photos/600/400?random=13",
    location: "Minato Ward",
    tips: "Go at sunset for amazing views. Booking online saves money. Best visited on clear days.",
    whyRecommended: ["Panoramic views", "Iconic landmark", "Day and night experiences"],
    tags: ["photography"],
    targetAgeGroups: ["18-24", "25-34", "35-49", "50-64"],
  },
  {
    id: "meiji-shrine",
    cityId: "tokyo",
    name: "Meiji Shrine",
    description:
      "Peaceful Shinto shrine surrounded by forest, dedicated to the Meiji Emperor and Empress",
    type: "hidden-gem",
    image:
      "https://picsum.photos/600/400?random=17",
    location: "Shibuya Ward",
    tips: "Visit early morning for peacefulspirit. Entry is free. Great for walking and meditation.",
    whyRecommended: ["Serene atmosphere", "Natural beauty", "Authentic experience"],
    tags: ["culture", "relaxation", "nature"],
    targetAgeGroups: ["25-34", "35-49", "50-64", "65+"],
  },
  {
    id: "sagrada-familia",
    cityId: "barcelona",
    name: "Sagrada Família",
    description:
      "Gaudí's unfinished masterpiece basilica with stunning architecture and intricate details",
    type: "must-see",
    image:
      "https://picsum.photos/600/400?random=21",
    location: "Eixample District",
    tips: "Book tickets in advance. Climb the towers for views. Allow 2-3 hours.",
    whyRecommended: ["Architectural masterpiece", "UNESCO World Heritage", "Inspiring design"],
    tags: ["art", "architecture", "culture"],
    targetAgeGroups: ["18-24", "25-34", "35-49", "50-64", "65+"],
  },
  {
    id: "park-guell",
    cityId: "barcelona",
    name: "Park Güell",
    description:
      "Gaudí's artistic park with colorful mosaics, unique structures, and panoramic city views",
    type: "must-see",
    image:
      "https://picsum.photos/600/400?random=25",
    location: "Gràcia District",
    tips: "Buy tickets online in advance. Visit early morning. Wear comfortable shoes.",
    whyRecommended: [
      "Colorful and whimsical",
      "Great views",
      "Unique artistic vision",
    ],
    tags: ["art", "shopping"],
    targetAgeGroups: ["18-24", "25-34", "35-49"],
  },
  {
    id: "eiffel-tower",
    cityId: "paris",
    name: "Eiffel Tower",
    description: "Iconic iron lattice tower and symbol of Paris built for the 1889 World's Fair",
    type: "must-see",
    image:
      "https://picsum.photos/600/400?random=29",
    location: "Champ de Mars",
    tips: "Book tickets in advance. Visit at night for magical lighting. Go early or late for fewer crowds.",
    whyRecommended: ["Iconic landmark", "Stunning views", "Romantic ambiance"],
    tags: ["photography", "art"],
    targetAgeGroups: ["18-24", "25-34", "35-49"],
  },
  {
    id: "louvre-museum",
    cityId: "paris",
    name: "Louvre Museum",
    description:
      "World's largest art museum housed in a former royal palace, featuring the Mona Lisa",
    type: "must-see",
    image:
      "https://picsum.photos/600/400?random=33",
    location: "Palais-Royal District",
    tips: "Reserve tickets online. Arrive early. Consider a guided tour. Plan 3-4 hours minimum.",
    whyRecommended: [
      "World-class art collection",
      "Iconic works",
      "Historic building",
    ],
    tags: ["art", "culture", "history"],
    targetAgeGroups: ["25-34", "35-49", "50-64", "65+"],
  },
  {
    id: "grand-palace-bangkok",
    cityId: "bangkok",
    name: "Grand Palace",
    description:
      "Stunning royal residence with intricate golden spires and the revered Emerald Buddha",
    type: "must-see",
    image:
      "https://picsum.photos/600/400?random=38",
    location: "Old City",
    tips: "Dress respectfully (covered shoulders and knees). Go early morning. Bring water.",
    whyRecommended: ["Sacred site", "Spectacular architecture", "Cultural significance"],
    tags: ["culture", "history"],
    targetAgeGroups: ["18-24", "25-34", "35-49", "50-64", "65+"],
  },
  {
    id: "chatuchak-market",
    cityId: "bangkok",
    name: "Chatuchak Weekend Market",
    description:
      "World's largest weekend market with over 15,000 stalls selling everything imaginable",
    type: "must-see",
    image:
      "https://picsum.photos/600/400?random=42",
    location: "Chatuchak",
    tips: "Go Saturday or Sunday. Arrive early to avoid crowds. Wear comfortable shoes.",
    whyRecommended: ["Unique shopping", "Local culture", "Great bargains"],
    tags: ["shopping"],
    targetAgeGroups: ["18-24", "25-34", "35-49"],
  },
  // Athens attractions
  {
    id: "parthenon-athens",
    cityId: "athens",
    name: "The Parthenon",
    description: "Ancient Greek temple dedicated to Athena, crowning the Acropolis",
    type: "must-see",
    image: "https://picsum.photos/600/400?random=46",
    location: "Acropolis",
    tips: "Visit early morning or sunset for best light and fewer crowds. Wear comfortable hiking shoes.",
    whyRecommended: ["Ancient wonder", "Architectural masterpiece", "Historical significance"],
    tags: ["history", "culture", "art"],
    targetAgeGroups: ["25-34", "35-49", "50-64", "65+"],
  },
  // Mexico City attractions
  {
    id: "frida-kahlo-museum",
    cityId: "mexico-city",
    name: "Frida Kahlo Museum",
    description: "Iconic blue house museum dedicated to the legendary Mexican artist",
    type: "must-see",
    image: "https://picsum.photos/600/400?random=50",
    location: "Coyoacán",
    tips: "Book tickets online. Best visited Tuesday-Thursday. Allow 1.5-2 hours.",
    whyRecommended: ["Artist's life story", "Authentic bohemian house", "Rich cultural insight"],
    tags: ["art", "culture", "history"],
    targetAgeGroups: ["18-24", "25-34", "35-49"],
  },
  // London attractions
  {
    id: "british-museum",
    cityId: "london",
    name: "British Museum",
    description: "World-renowned museum with artifacts from around the globe including the Rosetta Stone",
    type: "must-see",
    image: "https://picsum.photos/600/400?random=54",
    location: "Bloomsbury",
    tips: "Free entry. Very large, plan 3-4 hours minimum. Consider audio guide.",
    whyRecommended: ["Vast collection", "Free entry", "World history"],
    tags: ["culture", "history", "art"],
    targetAgeGroups: ["25-34", "35-49", "50-64", "65+"],
  },
  // Sydney attractions
  {
    id: "sydney-opera-house",
    cityId: "sydney",
    name: "Sydney Opera House",
    description: "Iconic and distinctive performing arts venue, a UNESCO World Heritage site",
    type: "must-see",
    image: "https://picsum.photos/600/400?random=58",
    location: "Bennelong Point",
    tips: "Book a show in advance. Take a guided tour. Visit at sunset.",
    whyRecommended: ["Iconic architecture", "World-class performances", "Stunning setting"],
    tags: ["art", "culture"],
    targetAgeGroups: ["18-24", "25-34", "35-49"],
  },
  {
    id: "bondi-beach",
    cityId: "sydney",
    name: "Bondi Beach",
    description: "Famous beach known for surfing, swimming, and coastal walks",
    type: "hidden-gem",
    image: "https://picsum.photos/600/400?random=61",
    location: "Eastern Suburbs",
    tips: "Go early morning for parking and fewer crowds. Beware of rip currents.",
    whyRecommended: ["Iconic beach", "Great surfing", "Scenic walks"],
    tags: ["adventure", "nature", "relaxation"],
    targetAgeGroups: ["18-24", "25-34", "35-49"],
  },
  // Rio attractions
  {
    id: "christ-redeemer",
    cityId: "rio-de-janeiro",
    name: "Christ the Redeemer",
    description: "Colossal statue overlooking Rio with panoramic views of the city and Guanabara Bay",
    type: "must-see",
    image: "https://picsum.photos/600/400?random=65",
    location: "Corcovado",
    tips: "Go early morning for best views and fewer tourists. Avoid during heavy rain.",
    whyRecommended: ["Iconic landmark", "Spectacular views", "Cultural symbol"],
    tags: ["photography", "history"],
    targetAgeGroups: ["18-24", "25-34", "35-49", "50-64"],
  },
  // Cairo attractions
  {
    id: "pyramids-of-giza",
    cityId: "cairo",
    name: "Pyramids of Giza",
    description: "Three largest pyramids of Egypt, including the Great Pyramid, one of the Seven Wonders",
    type: "must-see",
    image: "https://picsum.photos/600/400?random=70",
    location: "Giza Plateau",
    tips: "Hire a guide. Go early morning. Hire a camel for sunset views. Bring water and sunscreen.",
    whyRecommended: ["Ancient wonder", "Breathtaking scale", "Historical significance"],
    tags: ["history", "photography"],
    targetAgeGroups: ["25-34", "35-49", "50-64", "65+"],
  },
  // Venice attractions
  {
    id: "st-marks-basilica",
    cityId: "venice",
    name: "St. Mark's Basilica",
    description: "Byzantine masterpiece with golden mosaics and priceless artifacts",
    type: "must-see",
    image: "https://picsum.photos/600/400?random=74",
    location: "St. Mark's Square",
    tips: "Dress respectfully (covered shoulders/knees). Visit early morning or evening.",
    whyRecommended: ["Architectural marvel", "Sacred art", "Historical treasure"],
    tags: ["art", "culture", "history"],
    targetAgeGroups: ["25-34", "35-49", "50-64", "65+"],
  },
  // Kyoto attractions
  {
    id: "fushimi-inari-gates",
    cityId: "kyoto",
    name: "Fushimi Inari Shrine",
    description: "Famous shrine with thousands of vermillion torii gates winding up the mountain",
    type: "must-see",
    image: "https://picsum.photos/600/400?random=78",
    location: "Fushimi Ward",
    tips: "Go very early morning (before 7am) for solitude. Wear hiking shoes. Allow 2-3 hours.",
    whyRecommended: ["Iconic imagery", "Spiritual atmosphere", "Natural setting"],
    tags: ["nature", "culture", "photography"],
    targetAgeGroups: ["18-24", "25-34", "35-49"],
  },
  // Madrid attractions
  {
    id: "prado-museum",
    cityId: "madrid",
    name: "Prado Museum",
    description: "One of world's finest art museums with masterworks by Velázquez, Goya, and Bosch",
    type: "must-see",
    image: "https://picsum.photos/600/400?random=82",
    location: "Barrio de las Letras",
    tips: "Free last 2 hours before closing. Allow 3-4 hours minimum.",
    whyRecommended: ["World-class art", "Spanish masterpieces", "Cultural importance"],
    tags: ["art", "culture", "history"],
    targetAgeGroups: ["25-34", "35-49", "50-64", "65+"],
  },
  // Nice attractions
  {
    id: "promenade-des-anglais",
    cityId: "nice",
    name: "Promenade des Anglais",
    description: "Iconic 7km seafront boulevard with stunning Mediterranean views",
    type: "must-see",
    image: "https://picsum.photos/600/400?random=86",
    location: "Waterfront",
    tips: "Walk from west to east for best light. Rent bikes. Visit at sunset.",
    whyRecommended: ["Scenic walk", "Beach access", "Relaxing atmosphere"],
    tags: ["relaxation", "photography", "nature"],
    targetAgeGroups: ["18-24", "25-34", "35-49", "50-64"],
  },
];

export const mockRestaurants: Restaurant[] = [
  {
    id: "flavio-al-velavevodetto",
    cityId: "rome",
    name: "Flavio al Velavevodetto",
    description:
      "Traditional Roman restaurant serving authentic pasta and local specialties",
    category: "local-favorites",
    image:
      "https://picsum.photos/600/400?random=90",
    location: "Monti",
    cuisine: "Italian",
    priceLevel: "mid-range",
    whyRecommended: [
      "Authentic Roman cuisine",
      "Cozy atmosphere",
      "Reasonable prices",
    ],
    tags: ["food"],
    specialty: "Hand-made pasta and traditional Roman dishes",
  },
  {
    id: "alinea",
    cityId: "rome",
    name: "Alinea",
    description:
      "Michelin-starred restaurant offering innovative Italian cuisine with artistic presentation",
    category: "fine-dining",
    image:
      "https://picsum.photos/600/400?random=94",
    location: "Center",
    cuisine: "Italian (Modern)",
    priceLevel: "fine-dining",
    whyRecommended: ["Fine dining experience", "Innovative cuisine", "Impeccable service"],
    tags: ["food"],
    specialty: "Modern Italian with artistic plating",
  },
  {
    id: "pizza-da-enzo",
    cityId: "rome",
    name: "Pizza da Enzo",
    description: "Simple, authentic pizzeria in the heart of Rome with classic wood-fired ovens",
    category: "budget",
    image:
      "https://picsum.photos/600/400?random=98",
    location: "Centro Storico",
    cuisine: "Italian Pizza",
    priceLevel: "budget",
    whyRecommended: ["Authentic pizza", "Budget-friendly", "Local favorite"],
    tags: ["food"],
    specialty: "Traditional Roman pizza",
  },
  {
    id: "tsukiji-outer-market",
    cityId: "tokyo",
    name: "Tsukiji Outer Market",
    description:
      "Vibrant food market with fresh sushi, seafood, and street food stalls",
    category: "budget",
    image:
      "https://picsum.photos/600/400?random=1",
    location: "Tsukiji",
    cuisine: "Japanese Street Food",
    priceLevel: "budget",
    whyRecommended: ["Fresh sushi", "Local experience", "Budget-friendly"],
    tags: ["food"],
    specialty: "Fresh seafood and street food",
  },
  {
    id: "sukiyabashi-jiro",
    cityId: "tokyo",
    name: "Sukiyabashi Jiro",
    description: "Legendary 3-Michelin-star sushi restaurant",
    category: "fine-dining",
    image:
      "https://picsum.photos/600/400?random=4",
    location: "Ginza",
    cuisine: "Japanese Sushi",
    priceLevel: "fine-dining",
    whyRecommended: [
      "World-renowned",
      "Artistic sushi",
      "Unforgettable experience",
    ],
    tags: ["food"],
    specialty: "Premium nigiri sushi",
  },
  {
    id: "ramen-alley",
    cityId: "tokyo",
    name: "Ramen Alley",
    description:
      "Collection of tiny ramen shops with passionate owners serving perfect bowls",
    category: "local-favorites",
    image:
      "https://picsum.photos/600/400?random=8",
    location: "Shinjuku",
    cuisine: "Japanese Ramen",
    priceLevel: "budget",
    whyRecommended: ["Authentic ramen", "Local experience", "Affordable"],
    tags: ["food"],
    specialty: "Traditional tonkotsu ramen",
  },
  {
    id: "el-xampanyet",
    cityId: "barcelona",
    name: "El Xampanyet",
    description: "Historic tapas bar serving traditional Spanish fare and sparkling wine",
    category: "budget",
    image:
      "https://picsum.photos/600/400?random=12",
    location: "El Born",
    cuisine: "Spanish Tapas",
    priceLevel: "budget",
    whyRecommended: [
      "Historic establishment",
      "Authentic tapas",
      "Local favorite",
    ],
    tags: ["food"],
    specialty: "Traditional Spanish tapas",
  },
  {
    id: "caelis",
    cityId: "barcelona",
    name: "Caelis",
    description: "Michelin-starred restaurant offering French-Catalan cuisine",
    category: "fine-dining",
    image:
      "https://picsum.photos/600/400?random=15",
    location: "Eixample",
    cuisine: "French-Catalan",
    priceLevel: "fine-dining",
    whyRecommended: [
      "Michelin-starred",
      "Creative cuisine",
      "Elegant ambiance",
    ],
    tags: ["food"],
    specialty: "Modern French-Catalan fusion",
  },
  {
    id: "l-astrance",
    cityId: "paris",
    name: "L'Astrance",
    description: "3-Michelin-star restaurant offering innovative French cuisine",
    category: "fine-dining",
    image:
      "https://picsum.photos/600/400?random=19",
    location: "Passy",
    cuisine: "French",
    priceLevel: "fine-dining",
    whyRecommended: [
      "3 Michelin stars",
      "Innovative cuisine",
      "Exceptional service",
    ],
    tags: ["food"],
    specialty: "Modern French fine dining",
  },
  {
    id: "cafe-de-flore",
    cityId: "paris",
    name: "Café de Flore",
    description:
      "Historic café serving classic French bistro fare and people-watching opportunities",
    category: "mid-range",
    image:
      "https://picsum.photos/600/400?random=22",
    location: "Saint-Germain-des-Prés",
    cuisine: "French",
    priceLevel: "mid-range",
    whyRecommended: ["Historic café", "Iconic location", "Great atmosphere"],
    tags: ["food"],
    specialty: "Classic French bistro cuisine",
  },
  {
    id: "gaggan",
    cityId: "bangkok",
    name: "Gaggan",
    description:
      "Progressive Indian restaurant offering innovative small dishes and unique flavors",
    category: "fine-dining",
    image:
      "https://picsum.photos/600/400?random=26",
    location: "Silom",
    cuisine: "Indian (Modern)",
    priceLevel: "fine-dining",
    whyRecommended: ["Innovative cuisine", "Best restaurants list", "Unique experience"],
    tags: ["food"],
    specialty: "Progressive Indian small plates",
  },
  {
    id: "jay-fai",
    cityId: "bangkok",
    name: "Jay Fai",
    description:
      "Street food restaurant famous for crab omelet and one-woman show cooking",
    category: "budget",
    image:
      "https://picsum.photos/600/400?random=29",
    location: "Maha Nakhon",
    cuisine: "Thai Street Food",
    priceLevel: "budget",
    whyRecommended: [
      "Famous crab omelet",
      "Authentic experience",
      "Street food legend",
    ],
    tags: ["food"],
    specialty: "Legendary Thai street food",
  },
  // Athens restaurants
  {
    id: "taverna-psyrri-athens",
    cityId: "athens",
    name: "Taverna Psyrri",
    description: "Traditional family-run taverna with authentic Greek cuisine",
    category: "budget",
    image: "https://picsum.photos/600/400?random=33",
    location: "Psyrri District",
    cuisine: "Greek",
    priceLevel: "budget",
    whyRecommended: ["Authentic Greek food", "Family atmosphere", "Local favorite"],
    tags: ["food"],
    specialty: "Traditional Greek taverna dishes",
  },
  // Mexico City restaurants
  {
    id: "pujol-mexico",
    cityId: "mexico-city",
    name: "Pujol",
    description: "Chef's tasting menu featuring modern Mexican cuisine",
    category: "fine-dining",
    image: "https://picsum.photos/600/400?random=37",
    location: "Polanco",
    cuisine: "Mexican Modern",
    priceLevel: "fine-dining",
    whyRecommended: ["World-class cuisine", "Chef's innovation", "Mexican gastronomy"],
    tags: ["food"],
    specialty: "Modern Mexican tasting menu",
  },
  // London restaurants
  {
    id: "ivy-market-london",
    cityId: "london",
    name: "The Ivy Market Grill",
    description: "Contemporary British cuisine in a historic market setting",
    category: "fine-dining",
    image: "https://picsum.photos/600/400?random=40",
    location: "Covent Garden",
    cuisine: "British",
    priceLevel: "fine-dining",
    whyRecommended: ["British cuisine", "Historic venue", "Prime location"],
    tags: ["food"],
    specialty: "Contemporary British fare",
  },
  // Lisbon restaurants
  {
    id: "cafe-com-calma",
    cityId: "lisbon",
    name: "Café com Calma",
    description: "Casual café famous for breakfast and fresh pastries",
    category: "budget",
    image: "https://picsum.photos/600/400?random=43",
    location: "Bairro Alto",
    cuisine: "Portuguese",
    priceLevel: "budget",
    whyRecommended: ["Great breakfast", "Fresh pastries", "Local haunt"],
    tags: ["food"],
    specialty: "Portuguese breakfast and pastries",
  },
  // Sydney restaurants
  {
    id: "quay-sydney",
    cityId: "sydney",
    name: "Quay",
    description: "Chef's tasting menu with stunning Opera House views",
    category: "fine-dining",
    image: "https://picsum.photos/600/400?random=47",
    location: "Circular Quay",
    cuisine: "Modern Australian",
    priceLevel: "fine-dining",
    whyRecommended: ["Iconic views", "Fine dining", "Best restaurant"],
    tags: ["food"],
    specialty: "Modern Australian tasting menu",
  },
  // Rio restaurants
  {
    id: "confeitaria-colombo",
    cityId: "rio-de-janeiro",
    name: "Confeitaria Colombo",
    description: "Historic café from 1894 with traditional Brazilian treats",
    category: "budget",
    image: "https://picsum.photos/600/400?random=50",
    location: "Downtown",
    cuisine: "Brazilian",
    priceLevel: "budget",
    whyRecommended: ["Historic café", "Traditional treats", "Brazilian culture"],
    tags: ["food"],
    specialty: "Brazilian pastries and coffee",
  },
  // Cairo restaurants
  {
    id: "koshari-nile",
    cityId: "cairo",
    name: "Koshari Nile",
    description: "Legendary street food joint serving Egypt's favorite comfort dish",
    category: "budget",
    image: "https://picsum.photos/600/400?random=54",
    location: "Downtown",
    cuisine: "Egyptian",
    priceLevel: "budget",
    whyRecommended: ["Authentic koshari", "Street food legend", "Cheap and filling"],
    tags: ["food"],
    specialty: "Egyptian koshari",
  },
  // Venice restaurants
  {
    id: "cantina-momi",
    cityId: "venice",
    name: "Cantina do Momi",
    description: "Small bacaro (wine bar) with cicchetti (Venetian small bites)",
    category: "budget",
    image: "https://picsum.photos/600/400?random=57",
    location: "San Polo",
    cuisine: "Venetian",
    priceLevel: "budget",
    whyRecommended: ["Authentic bacaro", "Local experience", "Venetian cuisine"],
    tags: ["food"],
    specialty: "Venetian cicchetti and wine",
  },
  // Kyoto restaurants
  {
    id: "gion-tanto",
    cityId: "kyoto",
    name: "Gion Tanto",
    description: "Intimate kaiseki restaurant in the historic Gion district",
    category: "fine-dining",
    image: "https://picsum.photos/600/400?random=61",
    location: "Gion",
    cuisine: "Japanese Kaiseki",
    priceLevel: "fine-dining",
    whyRecommended: ["Traditional kaiseki", "Intimate setting", "Seasonal dishes"],
    tags: ["food"],
    specialty: "Japanese kaiseki tasting menu",
  },
  // Madrid restaurants
  {
    id: "el-club-all-day",
    cityId: "madrid",
    name: "El Club All Day",
    description: "Trendy café and restaurant with Spanish tapas and cocktails",
    category: "mid-range",
    image: "https://picsum.photos/600/400?random=64",
    location: "Malasaña",
    cuisine: "Spanish",
    priceLevel: "mid-range",
    whyRecommended: ["Modern Spanish", "Great cocktails", "Trendy vibe"],
    tags: ["food"],
    specialty: "Spanish tapas and cocktails",
  },
  // Nice restaurants
  {
    id: "chez-pipo",
    cityId: "nice",
    name: "Chez Pipo",
    description: "Family bistro famous for socca (chickpea crepes) and French Riviera cuisine",
    category: "budget",
    image: "https://picsum.photos/600/400?random=68",
    location: "Old Town",
    cuisine: "Provençal",
    priceLevel: "budget",
    whyRecommended: ["Famous socca", "Traditional Provençal", "Local favorite"],
    tags: ["food"],
    specialty: "Provençal socca and traditional dishes",
  },
];

export const mockActivities: Activity[] = [
  {
    id: "cooking-class-rome",
    cityId: "rome",
    name: "Roman Cooking Class",
    description:
      "Learn to prepare traditional Roman pasta and regional specialties from a local chef",
    image:
      "https://picsum.photos/600/400?random=71",
    category: "Food & Culture",
    duration: "3 hours",
    priceLevel: "mid-range",
    whyRecommended: [
      "Hands-on learning",
      "Authentic recipes",
      "Local experience",
    ],
    tags: ["food", "culture"],
  },
  {
    id: "catacomb-tour",
    cityId: "rome",
    name: "Catacombs Underground Tour",
    description:
      "Fascinating guided tour through ancient underground burial chambers with historical insights",
    image:
      "https://picsum.photos/600/400?random=75",
    category: "History",
    duration: "2-3 hours",
    priceLevel: "budget",
    whyRecommended: ["Historical", "Unique experience", "Educational"],
    tags: ["history", "culture"],
  },
  {
    id: "tea-ceremony-tokyo",
    cityId: "tokyo",
    name: "Traditional Tea Ceremony",
    description:
      "Experience the art of Japanese tea ceremony with a trained master in a peaceful setting",
    image:
      "https://picsum.photos/600/400?random=78",
    category: "Culture",
    duration: "1.5 hours",
    priceLevel: "mid-range",
    whyRecommended: [
      "Authentic culture",
      "Meditative experience",
      "Hands-on learning",
    ],
    tags: ["culture", "relaxation"],
  },
  {
    id: "temple-hop-tokyo",
    cityId: "tokyo",
    name: "Temple Hopping Bike Tour",
    description:
      "Cycle through quiet neighborhoods visiting hidden temples and experiencing local Tokyo",
    image:
      "https://picsum.photos/600/400?random=82",
    category: "Adventure",
    duration: "3 hours",
    priceLevel: "budget",
    whyRecommended: ["Active exploration", "Local experience", "Scenic views"],
    tags: ["nature", "adventure"],
  },
  {
    id: "gaudiBike-barcelona",
    cityId: "barcelona",
    name: "Gaudí Architectural Bike Tour",
    description:
      "Guided bike tour exploring Gaudí's modernist masterpieces and Barcelona's architecture",
    image:
      "https://picsum.photos/600/400?random=85",
    category: "Art & Culture",
    duration: "3.5 hours",
    priceLevel: "mid-range",
    whyRecommended: [
      "Expert commentary",
      "Multiple sites",
      "Physical activity",
    ],
    tags: ["art", "adventure"],
  },
  {
    id: "flamenco-show-barcelona",
    cityId: "barcelona",
    name: "Flamenco Dance Show",
    description:
      "Passionate flamenco performance with dinner in an intimate venue",
    image:
      "https://picsum.photos/600/400?random=88",
    category: "Entertainment",
    duration: "2 hours",
    priceLevel: "fine-dining",
    whyRecommended: [
      "Cultural performance",
      "Authentic entertainment",
      "Dinner included",
    ],
    tags: ["music", "food"],
  },
  {
    id: "seine-river-cruise",
    cityId: "paris",
    name: "Seine River Cruise",
    description:
      "Scenic boat tour along the Seine with illuminated monuments visible",
    image:
      "https://picsum.photos/600/400?random=92",
    category: "Scenic Tour",
    duration: "1-2 hours",
    priceLevel: "mid-range",
    whyRecommended: ["Iconic views", "Romantic atmosphere", "Relaxing"],
    tags: ["photography"],
  },
  {
    id: "muay-thai-class",
    cityId: "bangkok",
    name: "Muay Thai Boxing Class",
    description: "Learn authentic Muay Thai from professional trainers in a local gym",
    image:
      "https://picsum.photos/600/400?random=94",
    category: "Sport & Fitness",
    duration: "2 hours",
    priceLevel: "budget",
    whyRecommended: ["Unique experience", "Physical activity", "Local culture"],
    tags: ["adventure"],
  },
  {
    id: "floating-market",
    cityId: "bangkok",
    name: "Damnoen Saduak Floating Market",
    description:
      "Early morning boat tour of Bangkok's famous floating markets with vendors selling from boats",
    image:
      "https://picsum.photos/600/400?random=98",
    category: "Cultural Tour",
    duration: "4-5 hours",
    priceLevel: "budget",
    whyRecommended: ["Authentic Bangkok", "Unique experience", "Photo opportunities"],
    tags: ["food", "culture"],
  },
  // Athens activities
  {
    id: "acropolis-sunset-walk",
    cityId: "athens",
    name: "Acropolis Sunset Walk",
    description: "Guided walking tour ending with sunset at Acropolis viewpoint",
    image: "https://picsum.photos/600/400?random=1",
    category: "Guided Tour",
    duration: "4 hours",
    priceLevel: "mid-range",
    whyRecommended: ["Sunset views", "Historical insights", "Photography"],
    tags: ["history", "photography"],
  },
  // Mexico City activities
  {
    id: "tenochtitlan-day-trip",
    cityId: "mexico-city",
    name: "Tenochtitlan Day Trip",
    description: "Explore ancient Aztec ruins and float on Lake Chapultepec",
    image: "https://picsum.photos/600/400?random=4",
    category: "Day Trip",
    duration: "8 hours",
    priceLevel: "mid-range",
    whyRecommended: ["Archaeological sites", "Aztec history", "Traditional experience"],
    tags: ["history", "culture"],
  },
  // London activities
  {
    id: "thames-river-cruise",
    cityId: "london",
    name: "Thames River Cruise",
    description: "Scenic boat cruise from Westminster to Greenwich with Big Ben views",
    image: "https://picsum.photos/600/400?random=7",
    category: "Scenic Tour",
    duration: "1-2 hours",
    priceLevel: "mid-range",
    whyRecommended: ["River views", "Iconic landmarks", "Relaxing"],
    tags: ["photography"],
  },
  // Lisbon activities
  {
    id: "sintra-cascais-tour",
    cityId: "lisbon",
    name: "Sintra & Cascais Day Tour",
    description: "Full day tour to fairy-tale palaces and coastal cliffs",
    image: "https://picsum.photos/600/400?random=10",
    category: "Day Trip",
    duration: "10 hours",
    priceLevel: "mid-range",
    whyRecommended: ["Pena Palace", "Coastal views", "Fairy-tale setting"],
    tags: ["nature", "history"],
  },
  // Sydney activities
  {
    id: "bondi-coogee-walk",
    cityId: "sydney",
    name: "Bondi to Coogee Coastal Walk",
    description: "Scenic 6km clifftop walk along famous Sydney beaches",
    image: "https://picsum.photos/600/400?random=13",
    category: "Hiking",
    duration: "2 hours",
    priceLevel: "budget",
    whyRecommended: ["Beach views", "Coastal scenery", "Rock pools"],
    tags: ["nature", "adventure"],
  },
  // Rio activities
  {
    id: "favela-tour",
    cityId: "rio-de-janeiro",
    name: "Responsible Favela Tour",
    description: "Authentic community tour supporting local residents",
    image: "https://picsum.photos/600/400?random=16",
    category: "Cultural Tour",
    duration: "3 hours",
    priceLevel: "budget",
    whyRecommended: ["Local culture", "Community insight", "Street art"],
    tags: ["culture"],
  },
  // Cairo activities
  {
    id: "nile-felucca-cruise",
    cityId: "cairo",
    name: "Nile Felucca Sunset Cruise",
    description: "Traditional sailboat cruise on the Nile at golden hour",
    image: "https://picsum.photos/600/400?random=19",
    category: "Scenic Tour",
    duration: "2 hours",
    priceLevel: "mid-range",
    whyRecommended: ["Nile views", "Sunset", "Egyptian experience"],
    tags: ["nature", "photography"],
  },
  // Venice activities
  {
    id: "gondola-ride",
    cityId: "venice",
    name: "Traditional Gondola Ride",
    description: "Classic 30-minute gondola ride through Venice's iconic canals",
    image: "https://picsum.photos/600/400?random=22",
    category: "Scenic Tour",
    duration: "30 minutes",
    priceLevel: "budget",
    whyRecommended: ["Canal views", "Romantic", "Venetian tradition"],
    tags: ["culture"],
  },
  // Kyoto activities
  {
    id: "geisha-show-dinner",
    cityId: "kyoto",
    name: "Traditional Geisha Show & Dinner",
    description: "Authentic dinner show with geisha performance and Japanese cuisine",
    image: "https://picsum.photos/600/400?random=26",
    category: "Cultural Experience",
    duration: "2 hours",
    priceLevel: "fine-dining",
    whyRecommended: ["Geisha performance", "Traditional cuisine", "Cultural immersion"],
    tags: ["culture", "food"],
  },
  // Madrid activities
  {
    id: "flamenco-dinner-show",
    cityId: "madrid",
    name: "Flamenco Dinner Show",
    description: "Passionate flamenco performance with traditional Spanish dinner",
    image: "https://picsum.photos/600/400?random=29",
    category: "Cultural Experience",
    duration: "2.5 hours",
    priceLevel: "mid-range",
    whyRecommended: ["Live flamenco", "Spanish cuisine", "Cultural experience"],
    tags: ["culture", "food"],
  },
  // Nice activities
  {
    id: "french-riviera-cooking-class",
    cityId: "nice",
    name: "French Riviera Cooking Class",
    description: "Learn to prepare Provençal dishes in a local kitchen",
    image: "https://picsum.photos/600/400?random=32",
    category: "Culinary Experience",
    duration: "3 hours",
    priceLevel: "mid-range",
    whyRecommended: ["Cooking skills", "Local cuisine", "Culinary culture"],
    tags: ["food", "culture"],
  },
];

export const mockTravelTips: TravelTip[] = [
  {
    id: "rome-transport",
    cityId: "rome",
    category: "transport",
    title: "Getting Around Rome",
    content:
      "Buy a Roma Pass for unlimited public transport and discounted museum entries. Walking is often the best way to discover the city.",
  },
  {
    id: "rome-safety",
    cityId: "rome",
    category: "safety",
    title: "Safety Tips",
    content:
      "Keep valuables secure and be cautious of pickpockets in crowded areas. Avoid confrontations and trust your instincts.",
  },
  {
    id: "rome-timing",
    cityId: "rome",
    category: "timing",
    title: "Best Time to Visit",
    content:
      "April-May and September-October offer perfect weather. July-August is hot and crowded. December-February is quiet but cold.",
  },
  {
    id: "tokyo-transport",
    cityId: "tokyo",
    category: "transport",
    title: "Tokyo Metro System",
    content:
      "Get a Suica card for seamless travel on trains and buses. The metro is clean, efficient, and covers the entire city.",
  },
  {
    id: "tokyo-language",
    cityId: "tokyo",
    category: "general",
    title: "Language & Communication",
    content:
      "Learn basic Japanese phrases. Download a translation app. Younger staff at hotels and restaurants often speak English.",
  },
  {
    id: "barcelona-pickpockets",
    cityId: "barcelona",
    category: "safety",
    title: "Pickpocket Prevention",
    content:
      "Watch belongings carefully in crowded areas, especially on metro. Use anti-theft bags and keep valuables in hotel safes.",
  },
  {
    id: "paris-metro",
    cityId: "paris",
    category: "transport",
    title: "Paris Metro Ticket",
    content:
      "Buy a 10-carnet ticket pack for savings. Download RATP app for navigation. The metro is fast, frequent, and extensive.",
  },
  {
    id: "bangkok-taxis",
    cityId: "bangkok",
    category: "transport",
    title: "Bangkok Transportation",
    content:
      "Use Grab app for reliable taxis. BTS Sky Train covers major areas. Insist on meter usage or agree on price beforehand.",
  },
  {
    id: "bangkok-street-food",
    cityId: "bangkok",
    category: "general",
    title: "Street Food Safety",
    content:
      "Eat where locals eat. High turnover means food is fresh. Avoid ice in drinks. Bring antacids just in case.",
  },
  // Athens tips
  {
    id: "athens-walking",
    cityId: "athens",
    category: "transport",
    title: "Athens is Very Walkable",
    description: "Most attractions are within walking distance. Wear comfortable shoes for uneven streets.",
  },
  {
    id: "athens-siesta",
    cityId: "athens",
    category: "cultural",
    title: "Respect Greek Siesta",
    description: "Many shops close 2pm-5pm. Plan accordingly. Dinner starts late (9pm+).",
  },
  // Mexico City tips
  {
    id: "mexico-altitude",
    cityId: "mexico-city",
    category: "health",
    title: "Altitude Adjustment",
    description: "Mexico City is 2,250m high. Take it easy first day. Stay hydrated.",
  },
  {
    id: "mexico-safety",
    cityId: "mexico-city",
    category: "safety",
    title: "Be Street Smart",
    description: "Avoid displaying expensive items. Use Uber instead of street taxis. Explore with locals if possible.",
  },
  // London tips
  {
    id: "london-oyster",
    cityId: "london",
    category: "transport",
    title: "Get an Oyster Card",
    description: "Contactless payment is cheaper than buying individual tickets. Load credit daily.",
  },
  {
    id: "london-money",
    cityId: "london",
    category: "general",
    title: "London is Expensive",
    description: "Budget accordingly. Pubs offer good value meals. Many museums have free entry.",
  },
  // Lisbon tips
  {
    id: "lisbon-hills",
    cityId: "lisbon",
    category: "general",
    title: "Lisbon is Very Hilly",
    description: "Wear good walking shoes. Use the charming tram 28 to avoid steep climbs.",
  },
  {
    id: "lisbon-season",
    cityId: "lisbon",
    category: "timing",
    title: "Visit in Shoulder Season",
    description: "April-May or September-October offer perfect weather and fewer tourists than summer.",
  },
  // Sydney tips
  {
    id: "sydney-sun",
    cityId: "sydney",
    category: "health",
    title: "Beware the Sun",
    description: "UV levels are intense. Use SPF 50+ sunscreen. Apply frequently, especially near water.",
  },
  {
    id: "sydney-swimming",
    cityId: "sydney",
    category: "safety",
    title: "Swim Between the Flags",
    description: "Lifeguards patrol marked areas. Rip currents are common. Always check conditions.",
  },
  // Rio tips
  {
    id: "rio-transport",
    cityId: "rio-de-janeiro",
    category: "transport",
    title: "Use Registered Transport",
    description: "Avoid unmarked taxis. Use Uber, 99 app, or registered white cars with meter.",
  },
  {
    id: "rio-beaches",
    cityId: "rio-de-janeiro",
    category: "safety",
    title: "Beach Safety",
    description: "Avoid Flamengo beach at night. Leave valuables at hotel. Don't flaunt expensive items.",
  },
  // Cairo tips
  {
    id: "cairo-customs",
    cityId: "cairo",
    category: "cultural",
    title: "Respect Local Customs",
    description: "Conservative dress appreciated. Ramadan affects restaurant hours and alcohol availability.",
  },
  {
    id: "cairo-food",
    cityId: "cairo",
    category: "health",
    title: "Food and Water Safety",
    description: "Drink bottled water. Eat at established restaurants. Avoid ice. Bring antibiotic ointment.",
  },
  // Venice tips
  {
    id: "venice-transport",
    cityId: "venice",
    category: "transport",
    title: "Water Transport Passes",
    description: "Buy vaporetto passes for shorter stays. No cars allowed; water buses are main transport.",
  },
  {
    id: "venice-crowds",
    cityId: "venice",
    category: "timing",
    title: "Avoid Peak Hours",
    description: "Visit early morning or evening to enjoy Venice's magic with fewer tourists.",
  },
  // Kyoto tips
  {
    id: "kyoto-shoes",
    cityId: "kyoto",
    category: "cultural",
    title: "Shoe Etiquette Important",
    description: "Remove shoes in temples, homes, restaurants. Wear easy-on-easy-off footwear.",
  },
  {
    id: "kyoto-pocket-wifi",
    cityId: "kyoto",
    category: "general",
    title: "Get Pocket WiFi",
    description: "Rent a pocket WiFi device at airport for staying connected throughout Kyoto.",
  },
  // Madrid tips
  {
    id: "madrid-siesta",
    cityId: "madrid",
    category: "general",
    title: "Dinner Starts Late",
    description: "Restaurants rarely open before 8pm. Most locals dine 9pm-11pm. Plan accordingly.",
  },
  {
    id: "madrid-metro",
    cityId: "madrid",
    category: "transport",
    title: "Madrid Metro is Efficient",
    description: "Get a T-Casual ticket for 10 journeys. Metro is clean, safe, and covers the city well.",
  },
  // Nice tips
  {
    id: "nice-french",
    cityId: "nice",
    category: "general",
    title: "Learn Basic French",
    description: "English is less common here than other French cities. Learning key phrases helps significantly.",
  },
  {
    id: "nice-beach",
    cityId: "nice",
    category: "general",
    title: "Pebble Beaches are Uncomfortable",
    description: "Bring water shoes for beach comfort. Sunbeds are available for rent.",
  },
];

